yacy/yacy_net_homepage

docs/download_installation.md

Just changing a few typos ("klick" to "click"), and making a couple of changes to readability.

Typos and minor readability changes

---

docs/demonstration_tutorial_screenshot.md
docs/faq.md

I found some grammatical errors and awkward wordings in the Demo, so I thought I would help do what I can by changing some of them

Updating some grammatical errors

---

docs/download_installation.md

* Fixed PayPal logo when viewing this document outside of the main website.
* Attached command examples to points, rather than scattered throughout the explanation
* Changed some wording
* Fixed some capitalization
* Removed left-over Debian instructions
* Fixed Dockerub to Dockerhub (<- My original motivator to make this PR)
I can split these up if that would be preferable.

General cleanup of download_installation.md

---

docs/download_installation.md

Fixed a typo too!
Greetings from Liverpool!

Improved grammar of Download page

---

docs/contribute.md
docs/faq.md

objective: begin the docs fixing. 
documentation is probably the biggest pain. let's start here. 
added contribute.md, with a step-by-step code contribution guide. 
splited "technology" section into "usage", "indexing" and "DHT", reordered some questions and added some recent from forum. added several links. don't mind if anyone will find another logic of section names or structure, but let's have some.

faq.md mods and contribute.md

---

docs/faq.md

added a section with use cases.

faq: added section: what can i use yacy for?

---

docs/docs.md
docs/operation/ranking.md

transfered "Definition of Ranking Rules" from [legacy wiki](https://wiki.yacy.net/index.php/En:Ranking)

transfered ranking rules guide from old wiki

---

docs/docs.md

added a link to README.md at github

added a link to README.md at github

---

docs/docs.md
docs/operation/yacy_conf.md

created a basic page with yacy settings. 
basicaly a formated defaults and comments from yacy.init 
with the aim of easy searching from search engines, help-linking and quick reference.

created yacy settings page

---

docs/docs.md

added a link to https://yacy.net/material/Description_of_the_YaCy_Distributed_Web_Search_Engine_Herrmann_Ning_Diaz_Preneel_ESAT_KULeuven_COSIC_article-2459.pdf

added a link to description paper

---

docs/faq.md

minor fixes: added links, corrected stars in regexps

minor fixes/typos

---

docs/operation/yacy_conf.md

added new options introduced in https://github.com/yacy/yacy_search_server/pull/617 and https://github.com/yacy/yacy_search_server/pull/619 by @pr0vieh 
added a brief description of some debug options.

added new options + some debug options description

---

docs/docs.md
docs/faq.md
docs/operation/logging.md

exteded logging information and set-up into separate page in 'operation' section

added a yacy logging guide

---

docs/dev/solr.md
docs/dev/solrcloud.md
docs/docs.md

converted solr and solrcloud docs from the old wiki

converted solr docs from old wiki

---

docs/operation/ranking.md

* formatted a bit
* added information about 3 ranking setting - profiles and solr
* added ranking score visibility settings

formatted, added profiles and ranking score visibility settings

---

docs/docs.md
docs/installation/unix-fullinstall.md

* formatted a bit
* changed 'yacydm' username to 'yacyadm'
* moved file to unix-fullinstall.md
* added to index of docs

formatted, renamed and added a link to index

---

docs/docs.md
docs/installation/android.md

android installation guide, contributed by @jzacman via <https://github.com/yacy/yacy_search_server/issues/667>

android installation guide

---

docs/dev/solr-schema.md
docs/docs.md

compiled page describing yacy solr schema out of the source codes

added a solr schema description page

---

docs/demonstration_tutorial_screenshot.md
docs/download_installation.md
docs/index.md
docs/installation/headless.md

resolved conflicts and added fixes from #6 and from discussion entry by @genesisrefinedllc

fixed typos 

---

docs/docs.md
docs/installation/gnuinstall.md
docs/operation/crawlstart_p.md

* moved converted wiki entries to appropriate sections
* fixed images and hence the warnings

Resorted docs.md index and fixed the images

---

docs/operation/logging.md

Update logging.md to improve sentence structure, grammar
